try_compile(BUILD_CONFIGURE_SUCCESS
        PROJECT BUILDER
        SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}"
        BINARY_DIR "${CMAKE_CURRENT_LIST_DIR}/build"
)

set(CPPMAKE_BUILDER_CMD "${CMAKE_CURRENT_LIST_DIR}/build/builder${CMAKE_EXECUTABLE_SUFFIX}")
message(Running ${CPPMAKE_BUILDER_CMD})
execute_process(COMMAND ${CPPMAKE_BUILDER_CMD} WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/build)

include(build/generated.cmake)